// <auto-generated />
namespace MvcWk2App.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitializingDatabaseWithGames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitializingDatabaseWithGames));
        
        string IMigrationMetadata.Id
        {
            get { return "201902061540530_InitializingDatabaseWithGames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
